[versions]
configurate = "4.2.0-SNAPSHOT"
kotlin = "1.9.21"
log4j = "2.22.0"

[libraries]
adventure-bom = "net.kyori:adventure-bom:4.14.0"
annotations = "org.jetbrains:annotations:24.1.0"
brigadier = "com.mojang:brigadier:1.0.18"
configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-hocon = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
configurate-extra-kotlin = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate" }
exposed-bom = "org.jetbrains.exposed:exposed-bom:0.47.0"
exposed-core = { module = "org.jetbrains.exposed:exposed-core" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time" }
guava = "com.google.guava:guava:32.1.3-jre"
kbrig-brigadier = "org.anvilpowered:kbrig-brigadier:0.2.0-SNAPSHOT"
koin = "io.insert-koin:koin-core:3.5.2-RC1"
kotest = "io.kotest:kotest-runner-junit5-jvm:5.8.0"
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.2"
logging-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
logging-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
paper = "io.papermc.paper:paper-api:1.20.2-brigadier-SNAPSHOT"
postgresql = "org.postgresql:postgresql:42.7.0"
sponge = "org.spongepowered:spongeapi:8.2.0"
velocity = "com.velocitypowered:velocity-api:3.2.0-SNAPSHOT"

[bundles]
exposed = ["exposed-core", "exposed-dao", "exposed-jdbc", "exposed-java-time"]

[plugins]
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = "org.jlleitschuh.gradle.ktlint:11.6.1"
pluginyml = "net.minecrell.plugin-yml.paper:0.6.0"
shadow = "com.github.johnrengelman.shadow:8.1.1"
sponge = "org.spongepowered.gradle.plugin:2.2.0"
